name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting and Print goodbye
        run: |
            echo "Hello World"
            echo "Done - bye!"
